_format_version: "3.0"
_transform: true

services:
  - name: project-service
    url: http://project-service:6001
    routes:
      - name: project-route
        paths: [/project]
        strip_path: false
        
  - name: task-service
    url: http://task-service:6002
    routes:
      - name: task-route
        paths: [/task]
        strip_path: false
  - name: subtask-service
    url: http://subtask-service:6003
    routes:
      - name: subtask-route
        paths: [/subtask]
        strip_path: false
  - name: notification-service
    url: http://notification-service:6004
    routes:
      - name: notification-route
        paths: [/notification]
        strip_path: true
  - name: comment-service
    url: http://comment-service:6006
    routes:
      - name: comment-route
        paths: [/comments]
        strip_path: false


plugins:
  # Global CORS Plugin
  - name: cors
    enabled: true
    config:
      origins: ["*"]
      methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD]
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers: [X-Auth-Token]
      credentials: true
      max_age: 3600
      preflight_continue: false

  

