_format_version: "3.0"
_transform: true

services:
  - name: project-service
    url: http://project-service:6001
    routes:
      - name: project-route
        paths: [/project]
        strip_path: false






plugins:
  # Global CORS Plugin
  - name: cors
    enabled: true
    config:
      origins: ["*"]
      methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD]
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers: [X-Auth-Token]
      credentials: true
      max_age: 3600
      preflight_continue: false

  

